### ISSUE TITLE
Project update

### ISSUE THREAD

**Issue by paulocoutinhox** [mangelio/SimplePDFKit#2]
Hi,

You target "SimplePDFExample" need be defined as minimum version to 13.0 too (today is 12), because framework min version is 13.0.

And can you update the repository link to new repository in your readme?

Thanks.

**Comment by juliand665** [comment]
You're right! Not sure how I missed that. To be honest, the master branch is kind of in limbo right now… In baupen/iOS (our app using this library), I've switched to the SwiftPM version (`swift-package` branch), which no longer even uses PDFium because the built-in renderer has improved so much. I implemented your changes though :)
